services:

    traefik:
        image: traefik:v3
        command:
            - --api.dashboard=true
            - --providers.docker=true
            - --providers.docker.exposedByDefault=false
            - --entrypoints.web.address=:80
        ports:
            - "80:80"
            - "8088:8080"
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
        restart: unless-stopped

    email-service:
        build: ./email-service
        labels:
            - "traefik.enable=true"
            - "traefik.http.routers.ai-api.rule=Host(`email.localhost`)"
            - "traefik.http.routers.ai-api.entrypoints=web"
            - "traefik.http.services.ai-api.loadbalancer.server.port=8080"
        volumes:
            - ./email-service:/app
            - user_home:/home/appuser
        command: ["php","-S","0.0.0.0:8080","-t","public"]
        depends_on:
            - postgres
            - ollama
            - language-detector
        restart: unless-stopped

    language-detector:
        build: ./language-detector
        labels:
            - "traefik.enable=true"
            - "traefik.http.routers.lang.rule=Host(`language.localhost`)"
            - "traefik.http.routers.lang.entrypoints=web"
            - "traefik.http.services.lang.loadbalancer.server.port=8090"

    postgres:
        image: pgvector/pgvector:pg16
        environment:
            POSTGRES_DB: analyzer
            POSTGRES_USER: demo
            POSTGRES_PASSWORD: demo
        volumes:
            - pg_data:/var/lib/postgresql/data
            - ./postgres/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
        labels:
            - "traefik.enable=false"
        ports:
            -   "5432:5432"
        restart: unless-stopped

#    adminer:
#        image: adminer
#        restart: unless-stopped
#        environment:
#            ADMINER_DEFAULT_SERVER: postgres
#        labels:
#            - "traefik.enable=true"
#            - "traefik.http.routers.adminer.rule=Host(`db.localhost`)"
#            - "traefik.http.routers.adminer.entrypoints=web"
#            - "traefik.http.services.adminer.loadbalancer.server.port=8080"

    ollama:
        image: ollama/ollama:latest
        container_name: ollama
        labels:
            - "traefik.enable=true"
            - "traefik.http.routers.ollama.rule=Host(`llm.localhost`)"
            - "traefik.http.routers.ollama.entrypoints=web"
            - "traefik.http.services.ollama.loadbalancer.server.port=11434"
        volumes:
            - ollama_models:/root/.ollama/models
        # comment "deploy" to use CPU only
        deploy:
            resources:
                reservations:
                    devices:
                        - driver: nvidia
                          count: all
                          capabilities: [gpu]
        restart: unless-stopped

    embedding-service:
        build: ./embedding-service
        labels:
            - "traefik.enable=true"
            - "traefik.http.routers.embedding.rule=Host(`embedding.localhost`)"
            - "traefik.http.routers.embedding.entrypoints=web"
            - "traefik.http.services.embedding.loadbalancer.server.port=8091"
        restart: unless-stopped
        depends_on:
            -   postgres

#    weaviate:
#        image: semitechnologies/weaviate
#        labels:
#            - "traefik.enable=false"
#        environment:
#            QUERY_DEFAULTS_LIMIT: 20
#            AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED: "true"
#        restart: unless-stopped

volumes:
    user_home:
    ollama_models:
    pg_data:
