parameters:
    app.language_detector_url: '%env(LANGUAGE_DETECTOR_URL)%'
    app.ollama_url: '%env(OLLAMA_URL)%'
    app.ollama_model: '%env(OLLAMA_MODEL)%'
    app.ollama_temperature_incident: '%env(float:OLLAMA_TEMPERATURE_INCIDENT)%'
    app.ollama_temperature_emotions: '%env(float:OLLAMA_TEMPERATURE_EMOTIONS)%'
    app.language_detector_confidence_threshold: '%env(float:LANGUAGE_DETECTOR_CONFIDENCE_THRESHOLD)%'
    app.ollama_embedding_model: '%env(OLLAMA_EMBEDDING_MODEL)%'
    app.weaviate_url: '%env(WEAVIATE_URL)%'
    app.weaviate_similar_incident_limit: '%env(int:WEAVIATE_SIMILAR_INCIDENT_LIMIT)%'
    app.postgres_url: '%env(POSTGRES_URL)%'
    app.postgres_similar_incident_limit: '%env(int:POSTGRES_SIMILAR_INCIDENT_LIMIT)%'

services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\:
        resource: '../src/'

    App\Service\LanguageDetector\LanguageDetectorFastText:
        arguments:
            $baseUrl: '%app.language_detector_url%'
            $confidenceThreshold: '%app.language_detector_confidence_threshold%'

    App\Service\LLMExtractor\OllamaLLMExtractor:
        arguments:
            $baseUrl: '%app.ollama_url%'
            $model: '%app.ollama_model%'
            $temperatureIncident: '%app.ollama_temperature_incident%'
            $temperatureEmotions: '%app.ollama_temperature_emotions%'

    App\Service\EmbeddingService\OllamaEmbeddingService:
        arguments:
            $baseUrl: '%app.ollama_url%'
            $model: '%app.ollama_embedding_model%'

    App\Repository\WeaviateSimilarIncidentRepository:
        arguments:
            $baseUrl: '%app.weaviate_url%'
            $similarIncidentLimit: '%app.weaviate_similar_incident_limit%'

    Doctrine\DBAL\Connection:
        factory: ['App\Service\Shared\PostgresConnectionFactory', 'fromUrl']
        arguments:
            - '%app.postgres_url%'

    App\Repository\PostgresSimilarIncidentRepository:
        arguments:
            $similarIncidentLimit: '%app.postgres_similar_incident_limit%'

    App\Service\EmbeddingService\EmbeddingService: '@App\Service\EmbeddingService\OllamaEmbeddingService'

    App\EventListener\ExceptionListener:
        arguments:
            $appEnv: '%kernel.environment%'

    App\Service\LanguageDetector\LanguageDetector: '@App\Service\LanguageDetector\LanguageDetectorFastText'
    App\Service\LLMExtractor\LLMExtractor: '@App\Service\LLMExtractor\OllamaLLMExtractor'
    App\Repository\CandidateLocationRepository: '@App\Repository\InMemoryCandidateLocationRepository'
    App\Repository\CandidateDeviceRepository: '@App\Repository\InMemoryCandidateDeviceRepository'
    App\Repository\SimilarIncidentRepository: '@App\Repository\PostgresSimilarIncidentRepository'
